version: 0.1

devForm: https://docs.google.com/forms/d/e/1FAIpQLSc41GKKitf_6kXal5n4xIeSM_w0Czw2GX7-i8bIR0CJYLNG6A/viewform
devPost: https://docs.google.com/forms/u/0/d/e/1FAIpQLSc41GKKitf_6kXal5n4xIeSM_w0Czw2GX7-i8bIR0CJYLNG6A/formResponse

devMapping:
  tests:
    date: entry.1915046253
    result: entry.699482213
    isSubmitted: ''
    dateSubmitted: ''
    personal:
      firstName: entry.1278994752
      lastName: entry.1285649044
      vaccinationId: entry.992834568
      dob: entry.556991948
      gender: entry.1224698774
      village: entry.682058042
      conditions: entry.389107404
      phone: entry.1810101260
      email: entry.1016446264

liveForm: https://docs.google.com/forms/d/e/1FAIpQLSepjuDUzEza-YA0YUIr0bM8M4Jkn-tp6h1F1Cq6Zed1sBkRqQ/viewform
livePost: https://docs.google.com/forms/u/0/d/e/1FAIpQLSepjuDUzEza-YA0YUIr0bM8M4Jkn-tp6h1F1Cq6Zed1sBkRqQ/formResponse

liveMapping:
  tests:
    date: entry.1283207881
    result: entry.1395453298
    isSubmitted: ''
    dateSubmitted: ''
    personal:
      firstName: 	entry.590404003
      lastName: entry.1886925018
      vaccinationId: entry.1454131097
      dob: entry.1984486821
      gender: entry.1660490641
      village: entry.359444209
      conditions: entry.41058729
      phone: entry.1560344217
      email: entry.101602910
