name: Chrome E2E tests
on: [push]
# future use to limit tests
# on:
#   push:
#     branches:
#     - master

#     tags:
#     - '*'

#   pull_request:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: yarn test:e2e:ci:novid:chrome
          working-directory: q-app/quasar-project
          browser: chrome
